[IMP] open_academy: Add custom filter My courses to show just the current user's courses, also an option to group by responsibles' name T#52898
rolandojduartem/OpenAcademy pull request #10
Opened 2022-01-18 05:53 UTC by rolandojduartem

Now, if the user try to put a duplicated course's title, the app handles this constraint remarking the title is a copy.
![Screenshot from 2022-01-17 17-22-08](https://user-images.githubusercontent.com/90422721/149878034-69bbdb42-eb88-47e4-9754-e59b265e7edb.png)

 Also, the tree view of Session menu is going to be colorized by the duration value, if duration is less than 5, the color is blue and if duration is greater than 15, color is red.
![Screenshot from 2022-01-17 18-49-50](https://user-images.githubusercontent.com/90422721/149878319-f02432d3-1654-4486-8fe1-0e155b42ede1.png)

The calendar view was added for the user can see and add new sessions easily.
![Screenshot from 2022-01-17 19-44-05](https://user-images.githubusercontent.com/90422721/149878490-15e8901f-f7b6-4cca-a55d-93f4e77745eb.png)

And, now, the user have a custom filter that shows his / her courses and group by responsiles' names.
![Screenshot from 2022-01-17 23-22-52](https://user-images.githubusercontent.com/90422721/149878708-45b0570e-582c-4202-a7a2-0c3dad18d712.png)
![Screenshot from 2022-01-17 23-28-23](https://user-images.githubusercontent.com/90422721/149878725-6c1f1b63-90c8-4541-95a4-f4a0f8be58c4.png)

2022-01-18 21:12 UTC, rolandojduartem commented
Also I added the gantt view to show every session group by the instructor.
![Screenshot from 2022-01-18 15-08-17](https://user-images.githubusercontent.com/90422721/150019143-733f8324-5282-479e-9e62-7dcf2e54436f.png)

Add graph view tho show how many attendees there are on every session.
![Screenshot from 2022-01-18 15-10-08](https://user-images.githubusercontent.com/90422721/150019389-73023e1c-3c3f-4a24-8f70-7fbefe313809.png)

Finally, I added the kanban view to show by column the different sessions group by course id.
![Screenshot from 2022-01-18 15-11-44](https://user-images.githubusercontent.com/90422721/150019564-4cc5292f-d5da-485c-9307-e3321f1a85b2.png)

2022-01-18 21:15 UTC, rolandojduartem commented
Hi, @frahikLV , the pull request is ready, I am done with the constraints and advanced views sections. Could you review this PR?

2022-01-18 22:02 UTC, frahikLV requested changes
@rolandojduartem please address these changes

2022-01-18 22:02 UTC, frahikLV commented on open_academy/models/course.py
>  class Course(models.Model):
Forgot said this, but if you add `rec_name` to the model can use the title as record.name

```suggestion
class Course(models.Model):
    _name = 'course'
    _rec_name = 'title'
```

2022-01-19 03:30 UTC, rolandojduartem commented
Changes are ready, @frahikLV , could you review this PR?

2022-01-19 16:10 UTC, frahikLV approved these changes
@rolandojduartem Looks good, I will merge it

2022-01-19 16:10 UTC, merged