[IMP] open_academy: Add access rules to different kind of users ( admin, managers and user) where admin and managers have full access, while user can only read the information from Course and Session models. The Users and groups to test this functionality was added in this code T#52898
rolandojduartem/OpenAcademy pull request #11
Opened 2022-01-20 15:42 UTC by rolandojduartem

Add access to different kind of users (admin, manager and user) in the session and course model.
![Screenshot from 2022-01-19 16-16-17](https://user-images.githubusercontent.com/90422721/150371278-16d23bf6-2891-4b2c-9f76-9c6da599ec94.png)
![Screenshot from 2022-01-19 16-12-31](https://user-images.githubusercontent.com/90422721/150371301-cb724c87-a087-4206-95aa-af5d58d612ae.png)

Also, I added a recor rule to prevent the managers from updating records if there is a responsible assigned.
![Screenshot from 2022-01-20 09-31-57](https://user-images.githubusercontent.com/90422721/150371625-7cb9c6e4-b448-41bb-af5c-3946ea85a383.png)

2022-01-21 20:14 UTC, rolandojduartem commented
I added a wizard to let the user can update sessions with new attendees
![Screenshot from 2022-01-21 14-11-47](https://user-images.githubusercontent.com/90422721/150593969-46ab3092-ffbc-42f6-b144-6cff30ea3c54.png)

Also, I added the spanish translation.
![Screenshot from 2022-01-21 14-12-27](https://user-images.githubusercontent.com/90422721/150594077-3a36be14-e26f-4d2e-bcff-7211f252a891.png)

2022-01-21 20:16 UTC, rolandojduartem commented
@frahikLV, In this pull request, I finished security, wizard and internationalization sections from Odoo course. Could you review it please?

2022-01-21 22:31 UTC, frahikLV requested changes
@rolandojduartem can you address these changes?

2022-01-21 22:31 UTC, frahikLV commented on open_academy/data/ir_rule.xml
> +        <field name="name">There is a responsible already!!</field>
This is not a message, it's the name of the record
```suggestion
        <field name="name">Open Academy: Write or delete own courses</field>
```

2022-01-21 22:31 UTC, frahikLV commented on open_academy/demo/res_users.xml
> +    </record>
Move this to res.partner file

2022-01-21 22:31 UTC, frahikLV commented on open_academy/demo/res_users.xml
> +    </record>
move this to res.partner file

2022-01-21 22:31 UTC, frahikLV commented on open_academy/wizards/wizard_save_attendee.py
> +        default=lambda self: self.env['session'].browse(self._context.get('active_id'))
Remove this, please send the ids on the action call the ids via context with `default_session_ids` key

2022-01-21 22:31 UTC, frahikLV commented on open_academy/wizards/wizard_save_attendee.py
> +    _name = 'wizard_save_attendee'
change all the references of the name of the wizard from `wizard_save_attendee` to `assign.attendee.sessions`
modes `_name` don't use an underscore in the name, uses `.` , change this when you rename the wizard

2022-01-21 22:31 UTC, frahikLV commented on open_academy/wizards/wizard_save_attendee.py
> +class Wizard(models.TransientModel):
```suggestion
class AssignAttendeeSessions(models.TransientModel):
```

2022-01-21 22:31 UTC, frahikLV commented on open_academy/wizards/wizard_save_attendee.py
> +        self.session_ids.write({'attendee_ids': [Command.link(attendee.id) for attendee in self.attendee_ids]})
Add a validation that cannot assign more attendees than available seats

2022-01-21 22:31 UTC, frahikLV commented on open_academy/wizards/wizard_save_attendee.xml
> +            <form string="">
```suggestion
            <form>
```

2022-01-21 22:31 UTC, frahikLV commented on open_academy/wizards/wizard_save_attendee.py
> +    def save_several_session(self):
```suggestion
    def action_register_attendees_to_sessions(self):
```

2022-01-21 22:37 UTC, frahikLV requested changes
@rolandojduartem also fix this

2022-01-21 22:37 UTC, frahikLV commented on open_academy/data/ir_rule.xml
> +        <field name="groups" eval="[Command.link(ref('group_open_academy_manager'))]"/>
```suggestion
        <field name="groups" ref="group_open_academy_manager"/>
```

2022-01-21 22:38 UTC, frahikLV commented
Rename your PR and all the long commits with a short message... Say that doesn't import long messages, but, not too long...

2022-01-21 23:51 UTC, rolandojduartem commented on open_academy/data/ir_rule.xml
> +        <field name="groups" eval="[Command.link(ref('group_open_academy_manager'))]"/>
The original was fine. Done!

2022-01-22 05:48 UTC, rolandojduartem commented
@frahikLV changes were applied, I do not know if you are going to review it or Germana will do it.

2022-01-24 16:18 UTC, rolandojduartem commented
Hi, @goliveirab Francisco had left some commentaries and I tried to address the changes, could you review it, please?

2022-01-24 20:47 UTC, goliveirab commented
LGTM...

2022-01-24 22:50 UTC, merged