[IMP] open_academy: Update the start_date to show a default value that depends on the UTC of the user and also I added the is_active field with True as default value to show to the user if session is active or not T#52898
rolandojduartem/OpenAcademy pull request #8
Opened 2022-01-14 01:31 UTC by rolandojduartem

Now, if a user wants to add an instructor in Sessions, the user only can choose those partners if they are instructors or have any "Teacher" tag. Those tags were created in category.xml.
![Screenshot from 2022-01-13 18-11-39](https://user-images.githubusercontent.com/90422721/149435300-c4b3f876-a3ac-4a44-8821-a9d11ffdc08c.png)

Now, the user can put in taken seat how many seats are taken and can see the percentage of taken sets using the progress bar
![Screenshot from 2022-01-13 18-12-12](https://user-images.githubusercontent.com/90422721/149435437-dea86b83-4012-4781-b9b6-50b863c4f56b.png)

Finally, now, the star_date and active fields have default values to show the current date and the session are active.
![Screenshot from 2022-01-13 19-02-22](https://user-images.githubusercontent.com/90422721/149435611-a80fb3d6-cb4b-4455-ab32-9e89f0e2031a.png)

2022-01-15 05:30 UTC, rolandojduartem commented
Could you review this one, please, @frahikLV ?

2022-01-17 15:21 UTC, frahikLV requested changes
@rolandojduartem can you address these changes?

2022-01-17 15:21 UTC, frahikLV commented on open_academy/demo/category.xml
> +        <field name="color" eval="11"/>
Is this working? please change it to RGB color.

https://www.rapidtables.com/web/color/RGB_Color.html

2022-01-17 15:21 UTC, frahikLV commented on open_academy/demo/category.xml
> +    <record id="res_partner_category_15" model="res.partner.category">
Why the record id has the number 15?

`res_partner_category_15`

2022-01-17 15:21 UTC, frahikLV commented on open_academy/demo/category.xml
> +    <record id="res_partner_category_16" model="res.partner.category">
Why the record id has the number 16?

2022-01-17 15:21 UTC, frahikLV commented on open_academy/demo/category.xml
> +        <field name="color" eval="11"/>
Update to RGB color

2022-01-17 15:21 UTC, frahikLV commented on open_academy/demo/session.xml
> +      <field name='taken_seat'>10</field>
remove

2022-01-17 15:21 UTC, frahikLV commented on open_academy/models/session.py
> +                                                            "]"))
This looks ugly,

```suggestion
    instructor_id = fields.Many2one(
        "res.partner",
        domain=("['|', ('is_instructor', '=', 'True'), ('category_id.name', 'like', 'Teacher')]"),
    )
```

2022-01-17 15:21 UTC, frahikLV commented on open_academy/models/session.py
> +    taken_seat = fields.Integer(default=0)
Remove this field, use `attendee_ids` to compute the percentage instead, because you can have 10 taken seat, but not attendees, and viceversa

2022-01-17 15:21 UTC, frahikLV commented on open_academy/models/session.py
> +            }
Change `taken_seat` to `attendee_ids`

2022-01-17 16:51 UTC, frahikLV requested changes
@rolandojduartem test you code before request review

2022-01-17 16:51 UTC, frahikLV commented on open_academy/models/session.py
> +            }
`taken_seat` this field does not exist anymore. Please test the code before tag me.

2022-01-17 16:51 UTC, frahikLV commented on open_academy/models/session.py
> +    )
Again, looks bad, Check pythons PEP to best code practices, https://www.python.org/dev/peps/

```suggestion
    instructor_id = fields.Many2one(
        "res.partner",
        domain=("['|', ('is_instructor', '=', 'True'), ('category_id.name', 'like', 'Teacher')]"),
    )
```

2022-01-17 16:53 UTC, frahikLV commented
Please, don't do this
![image](https://user-images.githubusercontent.com/47753811/149810011-bd38da85-08c4-419d-9a1b-d4b096bad679.png)

2022-01-17 16:54 UTC, frahikLV commented
It is not a competition, check your code calmly before requesting changes.

2022-01-17 18:11 UTC, rolandojduartem commented
@frahikLV , now the changes were applied as you suggested, could you review this, please?

2022-01-17 18:13 UTC, frahikLV requested changes
@rolandojduartem The code LGTM, i will merge it

2022-01-17 18:14 UTC, frahikLV approved these changes
+1

2022-01-17 18:14 UTC, merged